### ISSUE TITLE
please support MacBook Pro '16 (Preinstalled macOS Catalina)

### ISSUE THREAD

**Issue by ukitomato** [tkkrr/your-mac-dict#2]
On mac where macOS Catalina is pre-installed, this extension cannot work because the dictionary path is different.

Dictionary Path
>/System/Library/AssetsV2/PreinstalledAssetsV2/InstallWithOs/com_apple_MobileAsset_DictionaryServices_dictionaryOSX/a27242716aafc5bee8a3c7290fb4c1cec87ed5fd.asset/AssetData/Sanseido\ The\ WISDOM\ English-Japanese\ Japanese-English\ Dictionary.dictionary

Hardware
-   Device name: MacBook Pro
-   Device ID: MacBookPro16, 1

**Comment by tkkrr** [comment]
please see #5 
Thanks.
